# Generated by Django 4.2.1 on 2023-05-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iss_2_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=2)),
                ('match', models.SmallIntegerField()),
                ('robot', models.CharField(max_length=6)),
                ('teamnumber', models.PositiveSmallIntegerField()),
                ('noshow', models.BooleanField()),
                ('location', models.CharField(max_length=6)),
                ('auto_upper_cone', models.PositiveSmallIntegerField()),
                ('auto_middle_cone', models.PositiveSmallIntegerField()),
                ('auto_lower_cone', models.PositiveSmallIntegerField()),
                ('auto_upper_cube', models.PositiveSmallIntegerField()),
                ('auto_middle_cube', models.PositiveSmallIntegerField()),
                ('auto_lower_cube', models.PositiveSmallIntegerField()),
                ('mobility', models.BooleanField()),
                ('auto_dock_engage', models.CharField(max_length=11)),
                ('teleop_upper_cone', models.PositiveSmallIntegerField()),
                ('teleop_middle_cone', models.PositiveSmallIntegerField()),
                ('teleop_lower_cone', models.PositiveSmallIntegerField()),
                ('teleop_upper_cube', models.PositiveSmallIntegerField()),
                ('teleop_middle_cube', models.PositiveSmallIntegerField()),
                ('teleop_lower_cube', models.PositiveSmallIntegerField()),
                ('teleop_pickup', models.CharField(max_length=10)),
                ('links', models.PositiveSmallIntegerField()),
                ('early_endgame', models.BooleanField()),
                ('endgame', models.CharField(max_length=11)),
                ('num_docked', models.PositiveSmallIntegerField()),
                ('skill', models.PositiveSmallIntegerField()),
                ('defense', models.PositiveSmallIntegerField()),
                ('died', models.BooleanField()),
                ('tipped', models.BooleanField()),
                ('card', models.BooleanField()),
                ('damage', models.BooleanField()),
                ('comments', models.TextField()),
                ('md5', models.CharField(max_length=64)),
            ],
        ),
    ]
