# Generated by Django 4.2.1 on 2023-06-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_remove_iss_2_input_id_alter_iss_2_input_md5'), ('api', '0003_iss_2_input_auto_pickup'), ('api', '0004_remove_iss_2_input_auto_pickup'), ('api', '0005_iss_2_input_auto_pickup'), ('api', '0006_alter_iss_2_input_md5'), ('api', '0007_alter_iss_2_input_defense_alter_iss_2_input_skill')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iss_2_input',
            fields=[
                ('names', models.CharField(max_length=2)),
                ('match', models.SmallIntegerField()),
                ('robot', models.CharField(max_length=6)),
                ('teamnumber', models.PositiveSmallIntegerField()),
                ('noshow', models.BooleanField()),
                ('location', models.CharField(max_length=6)),
                ('auto_upper_cone', models.PositiveSmallIntegerField()),
                ('auto_middle_cone', models.PositiveSmallIntegerField()),
                ('auto_lower_cone', models.PositiveSmallIntegerField()),
                ('auto_upper_cube', models.PositiveSmallIntegerField()),
                ('auto_middle_cube', models.PositiveSmallIntegerField()),
                ('auto_lower_cube', models.PositiveSmallIntegerField()),
                ('mobility', models.BooleanField()),
                ('auto_dock_engage', models.CharField(max_length=11)),
                ('teleop_upper_cone', models.PositiveSmallIntegerField()),
                ('teleop_middle_cone', models.PositiveSmallIntegerField()),
                ('teleop_lower_cone', models.PositiveSmallIntegerField()),
                ('teleop_upper_cube', models.PositiveSmallIntegerField()),
                ('teleop_middle_cube', models.PositiveSmallIntegerField()),
                ('teleop_lower_cube', models.PositiveSmallIntegerField()),
                ('teleop_pickup', models.CharField(max_length=10)),
                ('links', models.PositiveSmallIntegerField()),
                ('early_endgame', models.BooleanField()),
                ('endgame', models.CharField(max_length=11)),
                ('num_docked', models.PositiveSmallIntegerField()),
                ('skill', models.CharField(max_length=7)),
                ('defense', models.CharField(max_length=7)),
                ('died', models.BooleanField()),
                ('tipped', models.BooleanField()),
                ('card', models.BooleanField()),
                ('damage', models.BooleanField()),
                ('comments', models.TextField()),
                ('md5', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('auto_pickup', models.BooleanField(default=False)),
            ],
        ),
    ]
