# Generated by Django 4.2.1 on 2023-05-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iss_2_input',
            name='id',
        ),
        migrations.AlterField(
            model_name='iss_2_input',
            name='md5',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
