# Generated by Django 4.2.1 on 2023-06-03 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_iss_2_input_auto_pickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iss_2_input',
            name='auto_pickup',
        ),
    ]
