# Generated by Django 4.2.1 on 2023-06-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_iss_2_input_auto_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iss_2_input',
            name='md5',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
