from django.db import models

# Create your models here.
class iss_2_input(models.Model):
    username = models.CharField(max_length=50)
    names = models.CharField(max_length=2)
    match = models.SmallIntegerField()
    robot = models.CharField(max_length=6)
    teamnumber = models.PositiveSmallIntegerField()
    noshow = models.BooleanField()
    location = models.CharField(max_length=6)
    auto_upper_cone = models.PositiveSmallIntegerField()
    auto_middle_cone = models.PositiveSmallIntegerField()
    auto_lower_cone = models.PositiveSmallIntegerField()
    auto_upper_cube = models.PositiveSmallIntegerField()
    auto_middle_cube = models.PositiveSmallIntegerField()
    auto_lower_cube = models.PositiveSmallIntegerField()
    mobility = models.BooleanField()
    auto_pickup = models.BooleanField()
    auto_dock_engage = models.CharField(max_length=11)
    teleop_upper_cone = models.PositiveSmallIntegerField()
    teleop_middle_cone = models.PositiveSmallIntegerField()
    teleop_lower_cone = models.PositiveSmallIntegerField()
    teleop_upper_cube = models.PositiveSmallIntegerField()
    teleop_middle_cube = models.PositiveSmallIntegerField()
    teleop_lower_cube = models.PositiveSmallIntegerField()
    teleop_pickup = models.CharField(max_length=10)
    links = models.PositiveSmallIntegerField()
    early_endgame = models.BooleanField()
    endgame = models.CharField(max_length=11)
    num_docked = models.PositiveSmallIntegerField()
    skill = models.CharField(max_length=7)
    defense = models.CharField(max_length=7)
    died = models.BooleanField()
    tipped = models.BooleanField()
    card = models.BooleanField()
    damage = models.BooleanField()
    comments = models.TextField()
    md5 = models.CharField(max_length=100, primary_key=True)
